<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['table_field_label']=	array( 
	'tblsetting_scan' => [
		'id'	=>	'Mã',
		'setting_scan' => 'Tiêu đề',
		'dom_category' => 'Dom HTML Category',
		'dom_post_title' => 'Dom HTML Post Title',
		'dom_post_description' => 'Dom HTML Post Description',
		'dom_post_content' => 'Dom HTML Post Content',
		'is_href' => 'Link có URL home',
		'ordernum' => 'Thứ tự',
		'status'	=>	'Trạng thái',
	],
	'tblscan_post' => [
		'id' => 'Mã',
		'category' => 'Category',
		'category_sub' => 'Category Sub',
		'setting_scan_id' => 'Website cần quét',
		'link' => 'Link',
		'dom_status' => 'Lọc Theo',		
		'is_send' => 'Quét',		
		'ordernum' => 'Thứ tự',
		'status'	=>	'Trạng thái'
	],
	'tbluser'   =>  array(
		'id'    =>  'Mã',
		'username' =>  'Tài khoản',
		'password'   =>  'Mật khẩu',
		'image'	=>	'Ảnh đại diện',		
		'thumb' => 'Ảnh Thumb',
		'fullname' => 'Họ tên',
		'address' =>  'Địa chỉ',
		'phone'    =>  'Điện thoại',
		'email' =>  'Email',
		'info' => 'Giới thiệu',
		'post_date'  =>  'Ngày đăng ký',
		'ordernum' => 'Thứ tự',
		'status'    =>  'Trạng thái'
	),                     
	'tblarticle_category' =>  array(
		'id'    =>  'Mã',
		'category'   =>  'Danh mục bài viết',    
		'alias' =>  'Alias.(link dạng gioi-thieu.html,có thể để trống)',
		'parent_id' => 'Danh mục cha',  
		'image'	=>	'Icon',
		'thumb' => 'Icon Thumb',
		'home'=>'Hiện thị Home',          		                           
		'menu'    =>  'Hiện thị Menu',
		'footer'    =>  'Hiện thị Footer',
		'page_sub' => 'Hiện thị Page Con',
		'heading'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		'meta_title' => 'Meta Title',
		'meta_des'   => 'Meta Description',
		'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',
		'ordernum'  =>  'Thứ tự',
		'status'    =>  'Trạng thái'
	),                                  
	'tblarticle' =>  array(
		'id'    =>  'Mã',  
		'title' =>  'Tiêu đề', 
		'alias' =>  'Alias.(link dạng gioi-thieu.html,có thể để trống)',                                                                                                                           
		'category'   =>  'Danh mục bài viết cấp 1',
		'category_sub'    =>  'Danh mục bài viết cấp 2',				
		'description'    =>  'Tóm tắt',                                                                                                                                                                                        
		'image'       =>  'Ảnh đại diện (Kích thước: w <= 670px)',
		'image_square' => 'Ảnh vuông (Kích thước: w=150px, h=150px)',
		'thumb' =>  'Ảnh thumb',  
		'noibat' => 'Nổi bật',
		'hot' => 'Tin Hot',
		'content'   =>  'Nội dung',                                                                                                                                                                          
		'date_day'  =>  'Ngày đăng',		
		'author' =>  'Người đăng',                                                                                                                                                            
		'view'      =>  'Lượt xem',		
		'like_post' => 'Like',
		'meta_title' => 'Meta Title',
		'meta_des'   => 'Meta Description',
		'keyword'   =>  'Từ khóa (Hỗ trợ Seo)',               
		'ordernum'  =>  'Thứ tự',
		'status'    =>  'Trạng thái',
		'tag'       =>  'Tags (Các từ ngăn cách nhau bởi dấu phẩy)'
	),  	
	'tblcategory_ads' => [
		'id'	=>	'Mã',
		'category' => 'Danh mục bài viết',
		'category_ads' => 'Danh mục quảng cáo',
		'number_post' => 'Số bài viết hiện thị',
		'number_slider' => 'Số Slider hiện thị',
		'number_ads' => 'Số quảng cáo hiện thị',
		'number_post_same' => 'Số bài viết cùng loại',
		'ordernum'	=>	'Thứ tự',
		'status'	=>	'Trạng thái'
	], 	
	'tblads' => [
		'id'   =>  'Mã',
		'title'    =>  'Title ADS',
		'category_ads'   =>  'Danh mục Quảng cáo',		 
		'category'   =>  'Danh mục bài viết',	
		'image'  =>  'Ảnh đại diện',
		'image_square' => 'Ảnh vuông (Kích thước:150px x 150px)',
		'thumb'   =>  'Ảnh resize',
		'home' 		=> 'Hiện thị Trang chủ',
		'link' =>  'Link',			 
		'ordernum' =>  'Thứ tự',
		'status'   =>  'Trạng thái'   
   ],  
   'tblsetting_home' => [
	   'id'	=>	'Mã',
	   'post_number' => 'Số Post hiện thị',
	   'slider_number' => 'Số Slider hiện thị',
	   'ordernum' => 'Thứ tự',
	   'status'	=>	'Trạng thái'
   ],                                                                                                  								
	'tbladmin'   =>  array (
		'id'			=>'Mã',
		'username'		=>'Tên đăng nhập',
		'password'		=>'Mật khẩu',
		'name'			=>'Họ tên',
		'email'			=>'Email ',
		'phone'			=>'Phone',
		'address'		=>'Địa chỉ',
		'avatar'		=>	'Avatar',
		'thumb'		=>	'Ảnh Thumb',
		'role'		=>'Chọn quyền',
		'status'		=>'Trạng thái',				    
	),           					
	'tblinformation' => array(
		'id'    =>  'Mã',                                            
		'company_name'   =>  'Tên Website', 		
		'phone'	=> 'Điện thoại',		
		'fb_url' => 'Facebook',   
		'instagram_url' => 'Instagram',
		'g_plus_url' => 'Google +',
		'youtube' => 'Youtube',
		'ht'    =>  'Nội dung file .htaccess',
        'robot' =>  'Nội dung file robot.txt', 
		'logo'  =>  'Logo',
		'thumb' =>  'Ảnh thumb',  
		'google_map' => 'Code Google Map',
		'header'   =>  'Code Header',    
		'footer' => 'Code Footer',            
		'heading'  =>  'Thẻ Heading',                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			                
	),              
	'tblcontact' =>array(
		'id'    =>  'Mã',
		'name' =>  'Họ tên',
		'address'    =>  'Địa chỉ',
		'phone' =>  'Điện thoại',
		'email' =>  'Email',
		'content'   =>  'Nội dung',
		'date_contact'    =>  'Ngày liên hệ',
		'status'    =>  'Trạng thái'    
	),      
	'tblmeta'   => array(
		'id'    =>  'Mã',
		'title' =>  'Tiêu đề',
		'description'   =>  'Mô tả',
		'keyword'  =>  'Từ khóa'                
	),  
);