<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['field_col_add'] = array(  
	'tblsetting_scan' => [		
		'setting_scan' => 'col-lg-6',
		'dom_category' => 'col-lg-6',
		'dom_post_title' => 'col-lg-4',
		'dom_post_description' => 'col-lg-4',
		'dom_post_content' => 'col-lg-4',
		'is_href' => 'col-lg-12',
		'ordernum' => 'col-lg-12',
		'status'	=>	'col-lg-12',
	],
	'tblscan_post' => [	
		'category' => 'col-lg-4',
		'category_sub' => 'col-lg-4',	
		'setting_scan_id' => 'col-lg-4',
		'link' => 'col-lg-6',
		'dom_status' => 'col-lg-6',		
		'is_send' => 'col-lg-6',		
		'ordernum' => 'col-lg-12',
		'status'	=>	'col-lg-12'
	],     
	'tbluser'   =>  array(
		'username' =>  'col-lg-4',
		'password'   =>  'col-lg-4',
		'image'	=>	'col-lg-12',		
		'thumb' => 'col-lg-12',
		'fullname' =>  'col-lg-3',
		'address' =>  'col-lg-3',
		'phone'    =>  'col-lg-3',
		'email' =>  'col-lg-3',	
		'info' => 'col-lg-12',	
		'post_date'  =>  'col-lg-6',
		'ordernum' => 'col-lg-6',
		'status'    =>  'col-lg-12'
	),                     
	'tblarticle_category' =>  array(		
		'category'   	=>  'col-lg-12',    
		'alias' 		=>  'col-lg-12',
		'parent_id' 	=> 	'col-lg-12',  
		'image'	=>	'col-lg-12',
		'thumb' => 'col-lg-12',
		'home'			=>	'col-lg-3',          
		'menu'    		=>  'col-lg-3', 
		'footer'    	=>  'col-lg-3', 
		'page_sub' => 'col-lg-3',                           
		'heading'  		=>  'col-lg-12',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
		'meta_title' 	=> 	'col-lg-6',
		'meta_des'   	=> 	'col-lg-6',
		'keyword'   	=>  'col-lg-6',
		'ordernum'  	=>  'col-lg-6',
		'status'    	=>  'col-lg-12'
	),   
	'tblarticle' =>  array(		 
		'title' 		=>  'col-lg-12', 
		'alias' 		=>  'col-lg-12', 		                                                                                                                       
		'category'   	=>  'col-lg-6',
		'category_sub'  =>  'col-lg-6',		                                                                                                                                   
		'description'    	=>  'col-lg-12',                                                                                                                                                                                        
		'image'       	=>  'col-lg-6',
		'image_square' => 'col-lg-6',
		'thumb' 	=>  'col-lg-12',    
		'noibat' => 'col-lg-12',   
		'hot' => 'col-lg-12',     
		'content'   	=>  'col-lg-12',                                                                                                                                                                          
		'date_day'  	=>  'col-lg-4',		
		'author' 	=>  'col-lg-4',                                                                                                                                                            
		'view'      	=>  'col-lg-12',  		
		'like_post' => 'col-lg-12',                                                                                                                                                                                 
		'meta_title' 	=> 	'col-lg-6',
		'meta_des'   	=> 	'col-lg-6',
		'keyword'   	=>  'col-lg-6',               
		'ordernum'  	=>  'col-lg-6',
		'status'    	=>  'col-lg-12',
		'tag'       	=>  'col-lg-12',
	),    	
	'tblcategory_ads' => [		
		'category' => 'col-lg-6',
		'category_ads' => 'col-lg-6',
		'number_post' => 'col-lg-4',
		'number_ads' => 'col-lg-4',
		'number_ads' => 'col-lg-4',
		'number_post_same' => 'col-lg-6',
		'ordernum'	=>	'col-lg-6',
		'status'	=>	'col-lg-12'
	], 	 	
	'tblads' => [
		'title'    		=>  'col-lg-6',
		'category_ads'   =>  'col-lg-6',		
		'category'   =>  'col-lg-12',
		'image'  			=>  'col-lg-6',
		'image_square' => 'col-lg-6',
		'thumb'   	=>  'col-lg-12',
		'home'   	=>  'col-lg-12',
		'link' 			=>  'col-lg-6',				
		'ordernum' 		=>  'col-lg-6',
		'status'   		=>  'col-lg-12'   
	],   
	'tblsetting_home' => [		
		'post_number' => 'col-lg-4',
		'slider_number' => 'col-lg-4',
		'ordernum' => 'col-lg-4',
		'status'	=>	'col-lg-12'
	],                                                                                                                                    								
    'tbladmin'   =>  array (
		'username'		=>	'col-lg-4',
		'password'      => 	'col-lg-4',
		'name'			=> 	'col-lg-6',
		'email'			=>	'col-lg-6',
		'phone'			=>	'col-lg-6',
		'address'		=>	'col-lg-6',
		'avatar'		=> 	'col-lg-12',
		'role'			=>	'col-lg-12',
		'status'		=>	'col-lg-12',				    
    ),  
    'tblcontact' =>array(		
		'name' =>  'col-lg-4',
		'address'    =>  'col-lg-4',
		'phone' =>  'col-lg-4',
		'email' =>  'col-lg-4',
		'content'   =>  'col-lg-12',
		'date_contact'    =>  'col-lg-4',
		'status'    =>  'col-lg-12'    
    ),    
    'tblmeta'   => array(		
		'title' =>  'col-lg-6',
		'description'   =>  'col-lg-6',
		'keyword'  =>  'col-lg-12'                
    ),    
    'tblinformation' => array(		                                           
		'company_name'   =>  'col-lg-4',  		
		'phone' => 'col-lg-4',		
		'fb_url' =>  'col-lg-4',          		
		'instagram_url' =>  'col-lg-4',   
		'g_plus_url' =>  'col-lg-4',   
		'youtube' =>  'col-lg-4',   
		'ht'    =>  'col-lg-6',
        'robot' =>  'col-lg-6', 
		'logo'  =>  'col-lg-12',
		'thumb' =>  'col-lg-12',   		                                                                                                                                            
		'header'   =>  'col-lg-6',  
		'google_map' => 'col-lg-12',
		'footer' => 'col-lg-6',            
		'heading'  =>  'col-lg-12',                                                                                                                                                                                                                                                                                                                                                                                                                                                                    			                
	),   	
);